package com.resumebuilder.jdanalyzer.service;

import com.resumebuilder.jdanalyzer.config.ResumeBuilderProperties;
import com.resumebuilder.jdanalyzer.model.JdAnalysisResponse;
import com.resumebuilder.jdanalyzer.model.SynonymMatch;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.stream.Collectors;

@Service
public class AnalysisReportWriter {

    private static final DateTimeFormatter DATE = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    private final ResumeBuilderProperties properties;

    public AnalysisReportWriter(ResumeBuilderProperties properties) {
        this.properties = properties;
    }

    public String write(JdAnalysisResponse response, String slug) {
        String safeSlug = sanitizeSlug(slug);
        String fileName = "jd-match-" + safeSlug + "-" + LocalDate.now().format(DATE) + ".md";
        Path outputPath = properties.outputDir().resolve(fileName);

        try {
            Files.createDirectories(properties.outputDir());
            Files.writeString(outputPath, toMarkdown(response, safeSlug));
            return outputPath.toString();
        } catch (IOException e) {
            throw new IllegalStateException("Failed to write report: " + outputPath, e);
        }
    }

    private String toMarkdown(JdAnalysisResponse response, String slug) {
        StringBuilder md = new StringBuilder();
        md.append("# JD Match Report: ").append(slug).append("\n\n");
        md.append("**Generated:** ").append(LocalDate.now().format(DATE)).append("\n");
        md.append("**Analysis mode:** ").append(response.analysisMode()).append("\n");
        md.append("**Match score:** ").append(response.matchScore()).append("% (")
                .append(response.matchedCount()).append("/")
                .append(response.requiredCount()).append(" required keywords)\n\n");

        md.append("## Required keywords\n\n");
        appendList(md, response.requiredKeywords(), "*(none extracted)*");

        md.append("\n## Matched\n\n");
        appendList(md, response.matchedKeywords(), "*(none)*");

        md.append("\n## Missing (add to CV)\n\n");
        appendList(md, response.missingKeywords(), "*(none — great coverage!)*");

        md.append("\n## Nice-to-have\n\n");
        appendList(md, response.niceToHaveKeywords(), "*(none)*");

        md.append("\n## Matched nice-to-have\n\n");
        appendList(md, response.matchedNiceToHave(), "*(none)*");

        md.append("\n## Missing nice-to-have\n\n");
        appendList(md, response.missingNiceToHave(), "*(none)*");

        md.append("\n## Synonym / alias coverage\n\n");
        if (response.synonymMatches().isEmpty()) {
            md.append("*(no aliases loaded)*\n");
        } else {
            md.append("| JD term | Canonical | In resume? |\n");
            md.append("|---------|-----------|------------|\n");
            for (SynonymMatch match : response.synonymMatches()) {
                md.append("| ").append(match.jdTerm())
                        .append(" | ").append(match.canonicalTerm())
                        .append(" | ").append(match.presentInResume() ? "Yes" : "No")
                        .append(" |\n");
            }
        }

        md.append("\n## ATS flags\n\n");
        appendList(md, response.atsFlags(), "*(none)*");

        md.append("\n## Recommended projects to emphasize\n\n");
        appendList(md, response.recommendedProjects(), "*(no specific project mapping)*");

        md.append("\n---\n\n");
        md.append("*Generated by jd-analyzer. Update `career-master/cvs/` or project bullets — do not treat this file as master data.*\n");
        return md.toString();
    }

    private void appendList(StringBuilder md, java.util.List<String> items, String emptyText) {
        if (items == null || items.isEmpty()) {
            md.append(emptyText).append("\n");
            return;
        }
        md.append(items.stream().map(s -> "- " + s).collect(Collectors.joining("\n"))).append("\n");
    }

    private String sanitizeSlug(String slug) {
        if (slug == null || slug.isBlank()) {
            return "analysis";
        }
        return slug.toLowerCase()
                .replaceAll("[^a-z0-9]+", "-")
                .replaceAll("^-|-$", "");
    }
}
